# -*- coding: utf-8 -*-
"""create_baseline_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mDeKjl0TjcDo27aF_NuTxUTEc_gBl6Ui

### Import Libraries
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import warnings
warnings.filterwarnings("ignore", message=".*observed=False.*")

"""#### Load data (d_icd_diagnoses.csv and diagnoses_icd from the hosp folder)"""

df = pd.read_csv("d_icd_diagnoses.csv")
df.head()

df2 = pd.read_csv("diagnoses_icd.csv")
df2.head()

df2["icd_code"] = df2["icd_code"].astype(str)

df2["icd_code"] = (df2["icd_code"].str.strip().str.replace(".", "", regex=False).str.replace(",", "", regex=False))

"""#### diagnoses_icd has the details I need, so proceed with that and name it df2"""

len(df2)

"""#### Use ICD 9 and 10 codes to filter stroke cases. The resulting data is called df_stroke"""

# For ICD-9
stroke_icd9_prefixes = {
    "430", "431", "432", "433", "434", "436", "438", "V1254"
}

# For ICD-10
stroke_icd10_prefixes = [
    "I60", "I61", "I62", "I63", "I64", "I69", "Z8673"
]

def is_stroke_icd9(code_str: str) -> bool:
    """
    Return True if code_str corresponds to ICD-9 stroke codes.
    We match if the code_str starts with one of the 9-stroke codes (for 3-digit codes)
    or exactly equals a history code.
    """
    for pref in stroke_icd9_prefixes:
      if code_str.startswith(pref):
        return True
      if code_str == "V1254":
        return True
    return False

def is_stroke_icd10(code_str: str) -> bool:
    """
    Return True if code_str corresponds to ICD-10 stroke codes.
    We match if it starts with a known stroke prefix.
    """
    for pref in stroke_icd10_prefixes:
        if code_str.startswith(pref):
          return True
        if code_str == "Z8673":
          return True
    return False

mask = (
    ((df2["icd_version"] == 9) & (df2["icd_code"].apply(is_stroke_icd9))) |
    ((df2["icd_version"] == 10) & (df2["icd_code"].apply(is_stroke_icd10)))
)
df_stroke = df2[mask].copy()

print("Filtered stroke-related rows:", df_stroke.shape[0])
df_stroke.head()

"""#### Aggregate ICD codes for each stroke patient with commas for future classification"""

df_combined = (df2.groupby("subject_id")["icd_code"].agg(lambda x: ",".join(sorted(x.unique()))).reset_index())
df_combined.head()

df_combined[df_combined["icd_code"].str.contains(r"\b\d\b")]

df_combined.loc[df_combined["icd_code"].str.contains(r"\b\d\b"), ["subject_id", "icd_code"]]

df_combined.to_csv("df_combined.csv")

# Map grouped ICD codes into the original dataframe
df_stroke["icd_code"] = df_stroke["subject_id"].map(df_combined.set_index("subject_id")["icd_code"])
df_stroke.head()

df_stroke.to_csv("df_stroke.csv")

"""#### Remove duplicate entries and keep the last (assuming the most recent entry will record a death if there was one)"""

df_stroke_unique = df_stroke.drop_duplicates(subset=["subject_id"],  keep="last").copy()
print(f"Number of unique stroke cases: {len(df_stroke_unique)}")

"""#### Load patients data with biodata, including date of death, name it patient_info"""

patient_info = pd.read_csv("patients.csv")
patient_info.head()

patient_info.columns

"""#### Extract stroke patients' data in patient_info using subject ids from df_stroke"""

stroke_subject_ids = df_stroke["subject_id"].tolist()

# Merge stroke patients (with grouped ICD codes) and patient info
df_stroke_patients = (df_stroke_unique.merge(patient_info[["subject_id", "gender", "anchor_age", "dod"]],
               on="subject_id",
               how="inner"))[["subject_id", "icd_code", "gender", "anchor_age", "dod"]]

df_stroke_patients.head()

len(df_stroke_patients)

"""#### Create mortality column set to True if there is a date of death and False otherwise"""

df_stroke_patients["mortality"] = df_stroke_patients["dod"].notna().astype(int)
df_stroke_patients.head()

print("Number of stroke patients in patient info dataset: ", len(df_stroke_patients))

"""#### Load the admissions dataset to get more patient information"""

admissions_data = pd.read_csv("admissions.csv")
admissions_data.head()

admissions_data.columns

"""#### Filter the admissions dataset with subject ids of stroke patients from df_stroke"""

admissions_stroke_data = admissions_data.merge(df_stroke, on=["subject_id", "hadm_id"],how="inner")
admissions_stroke_data.head()

"""#### Remove duplicates from the admissions dataset, keeping the last entry (also based on the assumption that the last entry contains death information if there is any)"""

print("Number of stroke patients with data in admissions dataset with duplicates", len(admissions_stroke_data))

admissions_stroke_data_unique = admissions_stroke_data.drop_duplicates(subset=["subject_id"], keep="last").copy()

print("Number of stroke patients with data in admissions dataset without duplicates", len(admissions_stroke_data_unique))

admissions_stroke_data_unique.head()

"""#### Merge the data from the patient_info data and admissions data on the subject_id column"""

new_stroke_data = pd.merge(df_stroke_patients, admissions_stroke_data_unique, on="subject_id", how='left')
new_stroke_data.head()

new_stroke_data.columns

"""#### Trying to determine what date of death value to use, whether that from patient_info or admissions"""

new_stroke_data["dod"].isnull().sum()

new_stroke_data["deathtime"].isnull().sum()

"""#### The number of deaths recorded in the patient_info data is more than the number of deaths recorded in the admissions data. This makes sense because the data in patient_info comprises death both inside and outside the hospital"""

null_mask = new_stroke_data["dod"].isna() & new_stroke_data["deathtime"].notna()
null_dod_with_deathtime = new_stroke_data[null_mask]
print(len(null_dod_with_deathtime))

null_mask = new_stroke_data["deathtime"].isna() & new_stroke_data["dod"].notna()
null_deathtime_with_dod = new_stroke_data[null_mask]
print(len(null_deathtime_with_dod))

"""#### There is no instance where a patient is dead in admissions, but not dead in patient_info, which is good.  
There are 7057 instances where the patient is dead in patient_info, but is not dead in admissions (basically, the patient did not die while admitted in the hospital).  

The question now is, what date of death should be used? There's a tradeoff between data imbalance here and accuracy. If we use the date of death from admssions, we are sure that these patients died while admitted in the hospital for stroke, but we have very imbalanced data.  
Meanwhile, using the dod from patient_info handles some of the class imbalance, but we cannot say for sure that the patients died of stroke.
"""

without_dod = df_stroke_patients[df_stroke_patients["dod"].isna()]

with_dod = df_stroke_patients[df_stroke_patients["dod"].notna()]

"""#### Verify that for duplicates in the admissions data, the entry with a deathtime was selected
1) Using the date of death from the patient_info data, split the patient_info data into rows with dead patients and rows with living patients, keeping only the subject ids
2) For rows with living patients, simply merge with the admissions data.
3) For rows with dead patients, go back to the admissions data and filter duplicates, prioritizing rows with a deathtime value (assuming that the last entry will have the deathtime might have been a wrong assumption, the goal is to correct this).  
4) Merge the result of (3) with the admissions data.  
5) Join the data for living and dead patients
6) Merge the result with the rest of the patient_info data to get other details
"""

without_dod_ids = without_dod["subject_id"].tolist()

with_dod_ids = with_dod["subject_id"].tolist()

without_dod_join_admissions = admissions_stroke_data[admissions_stroke_data["subject_id"].isin(without_dod_ids)][["subject_id", "hadm_id", "admittime", "dischtime", "deathtime", "admission_type", "race", "marital_status"]].copy()
print("Number of stroke cases without dod (plus duplicates): ", len(without_dod_join_admissions))

# if any case has duplicates, count the number of duplicates,
# add column number of readmissions, which will be number of duplicates minus one
without_dod_join_admissions["number_of_readmissions"] = (without_dod_join_admissions.groupby("subject_id")["subject_id"].transform("count") - 1)

without_dod_join_admissions.head()

# Keep duplicate based on the time of admission
without_dod_join_admissions["admittime"] = pd.to_datetime(without_dod_join_admissions["admittime"])

# Sort by subject_id and admittime descending (most recent first)
without_dod_join_admissions_sorted = without_dod_join_admissions.sort_values(["subject_id", "admittime"], ascending=[True, False])

# Keep only the first row per subject_id (most recent)
without_dod_admissions_unique = without_dod_join_admissions_sorted.drop_duplicates(subset=["subject_id"], keep="first").copy()

print("Number of stroke cases without dod (most recent admission per patient):", len(without_dod_admissions_unique))

with_dod_join_admissions = admissions_stroke_data[admissions_stroke_data["subject_id"].isin(with_dod_ids)][["subject_id", "hadm_id", "admittime", "dischtime", "deathtime", "admission_type", "race", "marital_status"]].copy()
print("Number of stroke cases with dod (plus duplicates): ", len(without_dod_join_admissions))

# if any case has duplicates, count the number of duplicates,
# add column number of readmissions, which will be number of duplicates minus one
with_dod_join_admissions["number_of_readmissions"] = (with_dod_join_admissions.groupby("subject_id")["subject_id"].transform("count") - 1)

with_dod_join_admissions.head()

# Keep duplicates based on the one that has a deathtime, if not keep the first (dates are arranged in descending order)
with_dod_join_admissions["admittime"] = pd.to_datetime(with_dod_join_admissions["admittime"])
with_dod_join_admissions["deathtime_flag"] = with_dod_join_admissions["deathtime"].notna()
with_dod_admissions_sorted = with_dod_join_admissions.sort_values(by=["subject_id", "deathtime_flag", "admittime"],
                                                       ascending=[True, False, False])
with_dod_admissions_unique = with_dod_admissions_sorted.drop_duplicates(subset=['subject_id'], keep='first').copy()
with_dod_admissions_unique = with_dod_admissions_unique.drop(columns=['deathtime_flag'])
print("Unique admissions per patient (prioritizing deathtime):", with_dod_admissions_unique.shape[0])

with_dod_admissions_unique.head()

with_plus_without_dod = pd.concat([with_dod_admissions_unique, without_dod_admissions_unique], ignore_index=True)

full_df_nn = pd.merge(df_stroke_patients, with_plus_without_dod, on="subject_id", how="inner")
print("Length of full stroke data:", len(full_df_nn))

full_df_nn.head()

full_df_nn["subject_id"] = full_df_nn["subject_id"].astype(str)
full_df_nn["hadm_id"] = full_df_nn["hadm_id"].astype(str)
df_stroke["subject_id"] = df_stroke["subject_id"].astype(str)
df_stroke["hadm_id"] = df_stroke["hadm_id"].astype(str)

complete_df_nn = pd.merge(full_df_nn, df_stroke[["subject_id", "hadm_id", "icd_version"]], on=["subject_id", "hadm_id"], how="inner")
complete_df_nn = complete_df_nn.drop_duplicates(subset=["subject_id", "hadm_id"]).copy()
print("Length of full stroke data:", len(complete_df_nn))

complete_df_nn.head()

null_mask2 = complete_df_nn["deathtime"].isna() & complete_df_nn["dod"].notna()
null_deathtime_with_dod2 = complete_df_nn[null_mask2]
print(len(null_deathtime_with_dod2)) #5634

print("Number of dead patients", len(complete_df_nn[complete_df_nn["dod"].notna()]))

print("Number of living patients", len(complete_df_nn[complete_df_nn["dod"].isnull()]))

complete_df_nn.info()

complete_df_nn.describe()

"""### Change the class grouping to reflect the age when stroke risk rises (45) from Hayes (2010)

Kelly‐Hayes, M. (2010). Influence of age and health behaviors on stroke risk: lessons from longitudinal studies. Journal of the American Geriatrics Society, 58, S325-S328.
"""

age_bins= [17, 44, 64, 74, 84, 150]
labels = ["18–44", "45–64", "65–74", "75–84", "85+"]

complete_df_nn["age_group"] = pd.cut(complete_df_nn["anchor_age"], bins=age_bins, labels=labels, right=True, include_lowest=True)
print(complete_df_nn["age_group"].value_counts(dropna=False))
complete_df_nn[["anchor_age", "age_group"]].head()

# Age Distribution
age_order = [
    "18–44",
    "45–64",
    "65–74",
    "75–84",
    "85+"
]
sns.countplot(x="age_group", data=complete_df_nn, order=age_order)
plt.title("Age Range Distribution of Stroke Patients")
plt.xticks(rotation=45)
plt.show()

complete_df_nn.to_csv("complete_df_nn.csv")

full_df_nn.to_csv("full_df_nn.csv")

len(complete_df_nn)

len(full_df_nn)

