# -*- coding: utf-8 -*-
"""Copy of Mid_internship_presentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1praMiQYFkkpMlcZMStM5mE_ADXvaYhga
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

df = pd.read_csv("final_ml_data.csv")
df.head()

len(df)

df.columns

"""### Summary Statistics and Univariate Analysis"""

df.info()

df["age_group"].unique()

df["gender"].value_counts()

df["race"].value_counts()

sns.countplot(x="gender", data=df, edgecolor="black", palette={"M": "#00B1A4", "F": "salmon"})
plt.title("Sex Distribution in Stroke Patients")
plt.xticks([00,1], ["Male", "Female"])
plt.xlabel("Sex")
plt.savefig("sex_distribution.png", dpi=500)
plt.show()

sns.countplot(x="stroke_class", data=df, edgecolor="black", color="salmon")
plt.title("Distribution of Stroke Classes")
plt.xlabel("Stroke Class")
plt.ylabel("Count")
plt.xticks(rotation=90)
plt.tight_layout()
plt.savefig("class_count.png", dpi=500, bbox_inches='tight')
plt.show()

age_order = ["18–44","45–64","65–74","75–84","85+"]
sns.countplot(x="age_group", data=df, edgecolor="black", color="#00B1A4", order=age_order)
plt.title("Distribution of Age Groups")
plt.xlabel("Age Group")
plt.ylabel("Count")
plt.xticks()
plt.tight_layout()
plt.savefig("ageGroup_count.png", dpi=500, bbox_inches='tight')
plt.show()

df["race"] = df["race"].str.upper()
df["race"] = df["race"].apply(lambda x: "WHITE" if "WHITE" in x else "NON-WHITE")
df["race"].value_counts()

sns.countplot(x="race", data=df, edgecolor="black", palette={"WHITE": "#00B1A4", "NON-WHITE": "salmon"})
plt.title("Race Distribution")
plt.xlabel("Race")
plt.ylabel("Count")
plt.xticks()
plt.tight_layout()
plt.savefig("race_count.png", dpi=500, bbox_inches='tight')
plt.show()

ax = sns.countplot(
    x="race",
    data=df,
    edgecolor="black",
    palette={"WHITE": "#00B1A4", "NON-WHITE": "salmon"}
)

ax.set_xticklabels(["White", "Non-white"])

plt.title("Race Distribution")
plt.xlabel("Race")
plt.ylabel("Count")
plt.tight_layout()
plt.savefig("race_count.png", dpi=500, bbox_inches="tight")
plt.show()

"""### Create Visualizations"""

# Target variable
sns.countplot(x="mortality", data=df, edgecolor="black", palette={"0": "#00B1A4", "1": "salmon"})
plt.title("Mortality in Stroke Patients")
plt.xticks([0,1], ["Survived", "Died"])
plt.savefig("mortality_distribution.png", dpi=500)
plt.show()

# Sex distribution
sns.countplot(x="gender", data=df, edgecolor="black", color="#00B1A4")
plt.xlabel("Sex")
plt.title("Sex Distribution of Stroke Patients")
plt.xticks(["M","F"], ["Male", "Female"])
plt.savefig("sex_distribution_b.png", dpi=500)
plt.show()

# Death distribution by age group
age_order = ["18–44","45–64","65–74","75–84","85+"]
ratio_df = (df.groupby("age_group", observed=False)["mortality"].value_counts().unstack(fill_value=0).reset_index())
ratio_df.head()

ratio_df.columns

ratio_df.columns = ["age_group", "Alive", "Dead"]

ratio_df["living_to_dead_ratio"] = ratio_df["Alive"] / ratio_df["Dead"]

sns.barplot(x="age_group", y="Dead", data=ratio_df, order=age_order, edgecolor="black", color="#00B1A4")
plt.title("Mortality by Age Group")
plt.xlabel("Age Group")
plt.ylabel("Count")
plt.xticks()
plt.tight_layout()
plt.savefig("mortality_by_age_group.png", dpi=500, bbox_inches='tight')
plt.show()

sns.barplot(x="age_group", y="living_to_dead_ratio", data=ratio_df, order=age_order, edgecolor="black", color="#00B1A4")
plt.title("Ratio of Living to Dead Patients by Age Group")
plt.xlabel("Age Group")
plt.ylabel("Living-to-Dead Ratio")
plt.xticks()
plt.tight_layout()
plt.savefig("mortality_by_age_group_b.png", dpi=500, bbox_inches='tight')
plt.show()

# Death distribution by sex
sns.countplot(x="gender", hue="mortality", data=df, edgecolor="black", palette={0:"#00B1A4", 1: "salmon"})
plt.title("Death Distribution by Sex")
plt.xlabel("Sex")
plt.ylabel("Count")
plt.legend(title="mortality", labels=["Survived", "Died"])
plt.xticks(["M","F"], ["Male", "Female"])
plt.savefig("sex_death_distribution.png", dpi=500)
plt.show()

df.columns

# Prevalent icd code in dead patients
df["marital_status"].unique()

# Encode marital status
marital_status_mapping = {"MARRIED": "High", "SINGLE": "Medium", "DIVORCED": "Medium", "WIDOWED": "Low"}
df["care_level"] = df["marital_status"].map(marital_status_mapping)

# Death distribution by care level
care_order = ["Medium","High","Low"]
ratio_care = (df.groupby("care_level", observed=False)["mortality"].value_counts().unstack(fill_value=0).reset_index())
ratio_care.head()

ratio_care.columns = ["Care Level", "Alive", "Dead"]

ratio_care["living_to_dead_ratio"] = ratio_care["Alive"] / ratio_care["Dead"]

sns.barplot(x="Care Level", y="living_to_dead_ratio", data=ratio_care, order=care_order, edgecolor="black", color="#00B1A4")
plt.title("Ratio of Living to Dead Patients by Care Level")
plt.xlabel("Care Level")
plt.ylabel("Living-to-Dead Ratio")
plt.xticks()
plt.tight_layout()
plt.savefig("care_ratio_death.png", dpi=500, bbox_inches='tight')
plt.show()

df["stroke_class"].unique()

# Death distribution by stroke class
care_order = ["History of TIA", "Ischemic stroke","Hemorrhagic stroke",
              "Ischemic stroke + history of TIA","Hemorrhagic stroke + history of TIA"]
ratio_class = (df.groupby("stroke_class", observed=False)["mortality"].value_counts().unstack(fill_value=0).reset_index())
ratio_class.head()

ratio_class.columns = ["Stroke Class", "Alive", "Dead"]

ratio_class["living_to_dead_ratio"] = ratio_class["Alive"] / ratio_class["Dead"]

sns.barplot(x="Stroke Class", y="living_to_dead_ratio", data=ratio_class,  color="salmon", order=care_order, edgecolor="black")
plt.title("Ratio of Living to Dead Patients by Stroke Type")
plt.xlabel("Stroke Class")
plt.ylabel("Living-to-Dead Ratio")
plt.xticks(rotation=90)
plt.tight_layout()
plt.savefig("class_ratio_death.png", dpi=500, bbox_inches='tight')
plt.show()

# Stroke Classes
dead_patients = df[df["mortality"] == 1]
top_icd_codes = (dead_patients["stroke_class"].value_counts().head(10))

top_icd_codes.plot(kind="bar", edgecolor="black", color="salmon")
plt.title("Number of Deaths by Stroke Class")
plt.xlabel("Stroke Type")
plt.ylabel("Number of Deaths")
plt.xticks(rotation=90)
plt.tight_layout()
plt.savefig("stroke_type_death_toll.png", dpi=500, bbox_inches='tight')
plt.show()

# Death distribution over time
df_dead = df[df["dod"].notna()].copy()
df_dead["admitdate"] = df_dead["admittime_date"].str.split().str[0]
df_dead["admitdate"] = pd.to_datetime(df_dead["admitdate"], errors="coerce")
df_dead["dod"] = pd.to_datetime(df_dead["dod"], errors="coerce")

df_dead["days_to_death"] = (df_dead["dod"] - df_dead["admitdate"]).dt.days
df_dead = df_dead[df_dead["days_to_death"] >= 0]
len(df_dead)

df_first90 = df_dead[df_dead['days_to_death'] <= 90]
len(df_first90)

plt.hist(df_first90["days_to_death"], bins=15, color="salmon", edgecolor="black")
plt.title("Death Distribution Over 90 Days")
plt.xlabel("Days from Admission to Death")
plt.ylabel("Number of Patients")
#plt.grid(axis='y', alpha=0.7)
plt.tight_layout()
plt.savefig("dist_death.png", dpi=500, bbox_inches='tight')
plt.show()

df_within_one_day = df_first90[df_first90["days_to_death"] <= 1]
top_class_oneday = df_within_one_day["stroke_class"].value_counts()
print("Stroke Classes among patients who died within one day:")
print(top_class_oneday)

top_class_oneday.plot(kind="bar", color="salmon", edgecolor="black")
plt.title("Stroke Class Distribution Among Patients Who Died Within 1 Day of Admission")
plt.xlabel("Stroke Class")
plt.ylabel("Number of Patients")
plt.xticks(rotation=90)
plt.tight_layout()
plt.savefig("stroke_type_dead_one.png", dpi=500, bbox_inches='tight')
plt.show()

age_ratios_day1 = {"85+": [119,2721], "75-84":[105,4009], "65-74":[93,3522], "45-64":[94,3782], "18-44":[14,801]}
df_age = pd.DataFrame.from_dict(age_ratios_day1, orient='index', columns=['dead', 'alive']).reset_index()
df_age.columns = ['age_group', 'dead', 'alive']
df_age.head()

df_age["living_to_dead_ratio"] = df_age["alive"] / df_age["dead"]

order_age2 = ["18-44", "45-64", "65-74", "75-84", "85+"]

sns.barplot(x="age_group", y="living_to_dead_ratio", data=df_age, order= order_age2, edgecolor="black", color="#00B1A4")
plt.title("Ratio of Living to Dead Patients by Age Group After 1 Day of Admission")
plt.xlabel("Age Group")
plt.ylabel("Living-to-Dead Ratio")
plt.xticks()
plt.tight_layout()
plt.savefig("age_death_ratio.png", dpi=500, bbox_inches='tight')
plt.show()

# Blood Pressure
def classify_bp(value):
    # Handle nulls safely
    if pd.isna(value):
        return np.nan

    value = str(value).strip().lower()

    # Explicit label handling
    if value in ["normal"]:
        return "normal"
    if value in ["low", "high", "abnormal"]:
        return "abnormal"

    # Numeric BP (e.g. "120/80")
    try:
        systolic, diastolic = map(int, value.split("/"))

        if 91 <= systolic <= 129 and 61 <= diastolic <= 84:
            return "normal"
        else:
            return "abnormal"

    except Exception:
        return "abnormal"

df["blood_pressure"] = df["blood_pressure"].apply(classify_bp)

dead_patients = df[df["mortality"] == 1]
bp_mortality = dead_patients["blood_pressure"].value_counts()

bp_mortality.plot(kind="bar", color="salmon", edgecolor="black")
plt.title("Number of Deaths by Blood Pressure Class")
plt.xlabel("Blood Pressure")
plt.ylabel("Number of Deaths")
plt.xticks(rotation=0)
plt.tight_layout()
plt.savefig("blood_pressure_death_toll.png", dpi=500, bbox_inches='tight')
plt.show()

df["number_of_readmissions"].max()

marital_status_mapping = {1: "Dead", 0: "Alive"}
df["mortality_coded"] = df["mortality"].map(marital_status_mapping)

# Number of readmissions
grouped = df.groupby("mortality_coded")["number_of_readmissions"]
means = grouped.mean()
stds = grouped.std()
# Bar chart
plt.figure()
plt.bar(means.index, means.values, yerr=stds.values, capsize=5, color="#00B1A4")
plt.xlabel("Mortality")
plt.ylabel("Mean Number of Readmissions")
plt.title("Mean Readmissions by Mortality")
plt.tight_layout()
plt.show()

sns.violinplot(x ="mortality_coded", y ="number_of_readmissions", data = df, color="#00B1A4")
plt.title("Number of Readmissions by Mortality")
plt.xlabel("Mortality")
plt.ylabel("Number of Readmissions")
plt.tight_layout()
plt.savefig("readmissions_mortality_vp.png", dpi=500, bbox_inches='tight')
plt.show()

sns.boxplot(x="mortality_coded", y="number_of_readmissions", data=df, color="#00B1A4")
plt.title("Number of Readmissions by Mortality")
plt.xlabel("Mortality")
plt.ylabel("Number of Readmissions")
plt.tight_layout()
plt.savefig("readmissions_mortality_bp.png", dpi=500, bbox_inches='tight')
plt.show()

