# -*- coding: utf-8 -*-
"""add_clinical_notes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FZ9PrSLO326bLZ33ZmnXbAR0EkeLz3vu
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import warnings
import csv
warnings.filterwarnings("ignore", message=".*observed=False.*")

notes_path = "discharge.csv.gz"

"""#### Load output from create_basline_data.csv"""

stroke_df_path = "complete_df_nn.csv"

stroke_df = pd.read_csv(stroke_df_path)
stroke_patient_ids = stroke_df["subject_id"].tolist()
print(len(stroke_df), len(stroke_patient_ids))

"""#### Load file with clinical notes"""

notes = pd.read_csv(notes_path, parse_dates=["charttime","storetime"], compression='gzip')
notes.head()

stroke_df.head()

stroke_df["age_group"].unique()

"""#### Confirming that hadm_id is a unique identifier for the stroke notes"""

len(notes["hadm_id"].unique())

len(notes)

notes["text"].isnull().sum()

len(stroke_df)

"""#### Get notes for each patient based on subject_id and hadm_id"""

complete_stroke_data = notes.merge(stroke_df, on=["subject_id", "hadm_id"],how="inner")
print(len(complete_stroke_data))

complete_stroke_data.head()

stroke_df.columns

"""##### Some patients don't have clinical notes for the specific stroke-related hospital visit"""

complete_stroke_data.isnull().sum()

"""##### With all the preprocessing done, better to check that the mortality column was not compromised"""

check_mortality = (
    ((complete_stroke_data["dod"].isna()) & (complete_stroke_data["mortality"] != 0)) |
    ((~complete_stroke_data["dod"].isna()) & (complete_stroke_data["mortality"] != 1))
)
print("Number of inconsistent rows:", check_mortality.sum())

print("Length of the full dataset:", len(complete_stroke_data))

complete_stroke_data.drop_duplicates(subset=["subject_id", "hadm_id"],keep="first")
len(complete_stroke_data)

"""#### Format notes properly to fix intances that extend to more than one row"""

complete_stroke_data["text"] = complete_stroke_data["text"].replace({r'\r\n': ' ', r'\n': ' '}, regex=True)
complete_stroke_data.to_csv("complete_clean_data.csv", index=False, quoting=csv.QUOTE_ALL, escapechar="\\", encoding="utf-8")

df_complete = pd.read_csv("complete_clean_data.csv", quoting=csv.QUOTE_ALL, escapechar="\\", encoding="utf-8")
#assert complete_stroke_data.equals(df_complete)
#print("Data properly encoded!")

complete_stroke_data.columns

df_complete.head()

len(df_complete)